// Code generated by goctl. DO NOT EDIT.
// Source: filemeta.proto

package server

import (
	"context"

	"Gopan/app/filemeta/rpc/internal/logic"
	"Gopan/app/filemeta/rpc/internal/svc"
	"Gopan/app/filemeta/rpc/types/filemeta"
)

type FilemetaServer struct {
	svcCtx *svc.ServiceContext
	filemeta.UnimplementedFilemetaServer
}

func NewFilemetaServer(svcCtx *svc.ServiceContext) *FilemetaServer {
	return &FilemetaServer{
		svcCtx: svcCtx,
	}
}

func (s *FilemetaServer) GetFileMeta(ctx context.Context, in *filemeta.GetFileMetaReq) (*filemeta.FileMeta, error) {
	l := logic.NewGetFileMetaLogic(ctx, s.svcCtx)
	return l.GetFileMeta(in)
}

func (s *FilemetaServer) GetUserFileMeta(ctx context.Context, in *filemeta.GetUserFileMetaReq) (*filemeta.GetUserFileMetaResp, error) {
	l := logic.NewGetUserFileMetaLogic(ctx, s.svcCtx)
	return l.GetUserFileMeta(in)
}

func (s *FilemetaServer) UpdataUserFileMeta(ctx context.Context, in *filemeta.UpdataUserFileMetaReq) (*filemeta.CommonResp, error) {
	l := logic.NewUpdataUserFileMetaLogic(ctx, s.svcCtx)
	return l.UpdataUserFileMeta(in)
}
