// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"Gopan/service/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sendcode",
				Handler: SendcodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/github/login",
				Handler: GithubLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/github/callback",
				Handler: GithubCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/account"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/userinfo",
					Handler: userInfoHandler(serverCtx),
				},
			}...,
		),
	)
}
