// Code generated by goctl. DO NOT EDIT.
package types

type FileMeta struct {
	Id         int64  `json:"id"`
	FileSha1   string `json:"fileSha1"`
	FileSize   int64  `json:"fileSize"`
	FileName   string `json:"fileName"`
	FileAddr   string `json:"fileAddr"`
	Status     int64  `json:"status"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type UserFileMeta struct {
	Id         int64  `json:"id"`
	FileSha1   string `json:"fileSha1"`
	FileSize   int64  `json:"fileSize"`
	FileName   string `json:"fileName"`
	Status     int64  `json:"status"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type GetFileSha1Resp struct {
	FileSha1 string `json:"fileSha1"`
}

type GetFileMetaReq struct {
	FileSha1 string `json:"fileSha1"`
}

type GetFileMetaResp struct {
	FileMeta FileMeta `json:"fileMeta"`
}

type GetUserFileMetaResp struct {
	UserFileMetaList interface{} `json:"userFileMetaList"`
}

type UpdataUserFileMetaReq struct {
	FileName string `json:"fileName"`
	FileSha1 string `json:"fileSha1"`
}
