// Code generated by goctl. DO NOT EDIT.
package types

type DownloadMinioReq struct {
	FileSha1 string `json:"fileSha1"`
	FileName string `json:"fileName"`
	FileAddr string `json:"fileAddr"`
}

type DownloadCOSReq struct {
	FileSha1 string `json:"fileSha1"`
	FileName string `json:"fileName"`
	FileAddr string `json:"fileAddr"`
}
