// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"Gopan/app/filemeta/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/getfilesha1",
				Handler: GetFileSha1Handler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getfilemeta",
				Handler: GetFileMetaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/filemeta"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/getUserfilemeta",
					Handler: GetUserFileMetaHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/updatauserfilemeta",
					Handler: UpdataUserFileMetaHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/filemeta"),
	)
}
