// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"Gopan/app/download/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/download/minio",
					Handler: DownloadMinioHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/download/cos",
					Handler: DownloadCOSHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/file"), rest.WithTimeout(999000*time.Millisecond),
	)
}
