// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"Gopan/app/upload/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: fileUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/fastupload",
					Handler: tryFastFileUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/multipartupload/init",
					Handler: initialMultipartUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/multipartupload/uploadpart",
					Handler: uploadPartHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/multipartupload/completeuploadpart",
					Handler: CompleteUploadPartHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/file"),
	)
}
