name: Docker Build and Push
on:
#  release:
#   types: [published]  # 当发布一个新版本时触发，可选的事件类型还包括：created, edited, deleted, prereleased
  push:
    branches:
      - main

jobs:
  build-and-push-gopan-rmq:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push RMQ Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # 设置Dockerfile的上下文路径为根目录
        file: ./app/transfer/rmq/Dockerfile
        push: true
        tags: liuxian123/gopan-rmq:latest  # 替换为你的Docker Hub用户名和仓库名

  build-and-push-gopan-user-rpc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push RPC Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # 设置Dockerfile的上下文路径为根目录
        file: ./app/user/rpc/Dockerfile
        push: true
        tags: liuxian123/gopan-user-rpc/rpc:latest  # 替换为你的Docker Hub用户名和仓库名

  build-and-push-gopan-user-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push API Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # 设置Dockerfile的上下文路径为根目录
        file: ./app/user/api/Dockerfile
        push: true
        tags: liuxian123/gopan-user-api:latest  # 替换为你的Docker Hub用户名和仓库名
